version: '3'
services:

  djangoapp:
    restart: always
    build:
      context: .
    volumes:
      - .:/opt/uma/src/
    networks:
      - nginx_network

  nginx:
    restart: always
    image: nginx:stable
    ports:
      - 8001:80

    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - nginx_cache:/var/nginx/cache
    depends_on:
      - djangoapp
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
volumes:
  nginx_cache:

